### PR TITLE
Fixes for julia 0.7/1.0

### PR DESCRIPTION
**Pull request by donm**

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the contribution! Do you know if the 0.5 failures are know issues -- perhaps something generic related to running Julia in Travis? I don't think it should have become a problem without any changes in the actual code...

**Comment by waldyrious** [comment]
I think it makes sense to do those changes as part of this PR. Feel free to integrate them at your leisure :)

**Comment by donm** [comment]
Thanks for doing that, and sorry I didn't get to it as quickly as I thought I would.

**Comment by waldyrious** [comment]
No worries, you did the bulk of the work on this PR -- it was only fair that someone else do the work of integrating changes made elsewhere ;)

**Pull request merged**
