### PR TITLE
Enable precompilation

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the PR! Just for completeness, could you add a comment linking to https://docs.julialang.org/en/stable/manual/modules/#module-initialization-and-precompilation above that line?

**Comment by giordano** [comment]
I added a reference to https://docs.julialang.org/en/latest/manual/modules.html#Module-initialization-and-precompilation-1, the above link would be broken after release of Julia 0.6.

Would you tag a new version of `Tau` after this PR is merged?  Thanks!

**Comment by giordano** [comment]
Yes, I'd be honored, thanks :-)

**Comment by waldyrious** [comment]
Invite sent!

**Pull request merged**
